### ISSUE TITLE
Class naming conflict

### ISSUE THREAD

**Issue by rcastagno** [magnetsystems/r2m-plugin-android#20]
I'm trying to call different services which follows the following schema for the returned object:

{
  "status": 0,
  "result":  jaddajaddajadda
}

where "status" indicates if the call is OK or there have been errors, and result is used for returning the actual data.

Problem is, there are in this way several services which returns the same keys, but magnet tries to generate a Result class each time, resulting in a naming conflict.

Is there any way or best practice I can follow to deal with this services?

Thanks a lot!

**Comment by etexier** [comment]
If you use rest2mobile to generate multiple services and either the request and response json elements may conflict in name (in this case, "result"). You can segregate the generated class them by using a different package name (specified with "Package Name" entry in the "Add REST API" ). 

In this case, you must create 2 different class/api since you obviously can't generate 2 different methods with 2 different package for the same class.

Would that help in your case?

**Comment by rcastagno** [comment]
That was the solution I was thinking about, just wanted to be sure it was the best one. 
Thanks!

**Comment by etexier** [comment]
Glad to see it helped.
